name: Articles
description: 'Articlepulsehub articles storage content type.'
machine_name: content_articles
created: '2025-08-24 09:00 AM'
fields:
    content_articles_field_cover_image:
        label: 'Cover Image'
        type: file
        name: content_articles_field_cover_image
        id: ''
        class:
            - ''
        default_value: ''
        required: false
        handler: Simp\Core\components\basic_fields\FileField
        limit: 1
        settings:
            allowed_file_types:
                - image/webp
            allowed_file_size: '1000000'
    content_articles_field_other_images:
        label: 'Other Images'
        type: file
        name: content_articles_field_other_images
        id: ''
        class:
            - ''
        default_value: ''
        required: false
        handler: Simp\Core\components\basic_fields\FileField
        limit: 10
        settings:
            allowed_file_types:
                - 'image/*'
            allowed_file_size: '5000000'
    content_articles_field_category:
        label: Category
        type: reference
        name: content_articles_field_category
        id: ''
        class:
            - ''
        default_value: ''
        required: false
        handler: Simp\Core\components\reference_field\ReferenceField
        limit: 5
        reference:
            type: term
            reference_entity: categories
    content_articles_field_tags:
        label: Tags
        type: reference
        name: content_articles_field_tags
        id: ''
        class:
            - ''
        default_value: ''
        required: false
        handler: Simp\Core\components\reference_field\ReferenceField
        limit: 5
        reference:
            type: term
            reference_entity: tags
    content_articles_field_body:
        label: Body
        name: content_articles_field_body
        id: ''
        class:
            - ''
            - editor
        default_value: ''
        required: false
        handler: Simp\Core\components\basic_fields\TextAreaField
        limit: 1
        options:
            rows: '20'
            cols: '20'
        type: textarea
    content_articles_field_featured:
        label: Featured
        name: content_articles_field_featured
        id: ''
        class:
            - ''
        default_value: ''
        type: checkbox
        required: false
        limit: 1
        handler: Simp\Core\components\basic_fields\CheckboxField
        checkboxes:
            - 'Yes'
            - 'No'
    content_articles_field_comments:
        label: Comments
        type: form_builder
        name: content_articles_field_comments
        id: ''
        class:
            - ''
        default_value: ''
        required: false
        handler: Simp\Core\extends\form_builder\src\Field\FormBuilderField
        limit: 200
        settings:
            show_as: comments_form
            form_visible: true
display_setting:
    content_articles_field_cover_image:
        display_label: '1'
        display_as: image
        display_enabled: '1'
    content_articles_field_other_images:
        display_label: '1'
        display_as: image
        display_enabled: '1'
    content_articles_field_category:
        display_label: '1'
        display_as: reference
        display_enabled: '1'
    content_articles_field_tags:
        display_label: '1'
        display_as: reference
        display_enabled: '1'
    content_articles_field_body:
        display_label: '1'
        display_as: p
        display_enabled: '1'
    content_articles_field_featured:
        display_label: '1'
        display_as: p
        display_enabled: '1'
    content_articles_field_comments:
        display_label: '1'
        display_as: p
        display_enabled: '1'
permission:
    - administrator
    - authenticated
    - manager
    - content_creator
    - anonymous
storage:
    2: node__content_articles_field_cover_image
    5: node__content_articles_field_other_images
    9: node__content_articles_field_category
    14: node__content_articles_field_tags
    19: node__content_articles_field_body
    25: node__content_articles_field_featured
    32: node__content_articles_field_comments
